repos:
- repo: local
  hooks:
  - id: shellcheck
    name: shellcheck
    language: system
    files: "^(bin/|lib/)"
    pass_filenames: false
    verbose: true
    entry: scripts/shellcheck.bash
  - id: shfmt
    name: shfmt
    language: system
    files: "^(bin/|lib/)"
    pass_filenames: false
    verbose: true
    entry: scripts/shfmt.bash
